Update HSTU (#199)
Summary:
Updating HSTU to fix the following failure:

  File "/home/hoy/tritonbench/tritonbench/operators/ragged_attention/operator.py", line 73, in <lambda>
    return lambda: triton_hstu_mha(
                   ^^^^^^^^^^^^^^^^
TypeError: triton_hstu_mha() missing 1 required positional argument: 'causal'

Pull Request resolved: https://github.com/pytorch-labs/tritonbench/pull/199

Reviewed By: xuzhao9

Differential Revision: D73019243

Pulled By: htyu

fbshipit-source-id: d00a6f0f973e2a3b0ff2ffd1c40faff8305ff332