Remove triton_tutorial_flash_v2_tma from SL periodic run
Summary:
Jobs like https://www.internalfb.com/servicelab/experiment/5401578856 actually fails without generating any metrics because the triton_tutorial_flash_v2_tma backend will fail with logs:

```
AttributeError: module 'triton.language' has no attribute 'make_tensor_descriptor'
```

Reviewed By: dhruvak3

Differential Revision: D75998668

fbshipit-source-id: f0a1424e63ad7252c5a1a97dfe3a9fc45f5ec81b