Add an init file to tools so that it is considered as an module. (#48)
Summary:
Fixing issues like:

  File "tritonbench/install.py", line 8, in <module>
    from tools.cuda_utils import CUDA_VERSION_MAP, DEFAULT_CUDA_VERSION
ModuleNotFoundError: No module named 'tools.cuda_utils'

Pull Request resolved: https://github.com/pytorch-labs/tritonbench/pull/48

Reviewed By: xuzhao9

Differential Revision: D65916686

Pulled By: htyu

fbshipit-source-id: cf2693b8b9496f08e75aae97709a7affaa53300b