Fix FileNotFoundError during plot
Summary:
While running the `jagged_sum` kernel with `--plot`, I encountered the following error since the parent directories does not exsit.

```
Traceback (most recent call last):
  File "/data/users/shawnzhong/fbsource/buck-out/v2/gen/fbcode/14ceee714108d25d/pytorch/tritonbench/__run__/run#link-tree/__run_lpar_main__.py", line 38, in <module>
    __invoke_main()
  File "/data/users/shawnzhong/fbsource/buck-out/v2/gen/fbcode/14ceee714108d25d/pytorch/tritonbench/__run__/run#link-tree/__run_lpar_main__.py", line 35, in __invoke_main
    run_as_main(module, main_function)
  File "/data/users/shawnzhong/fbsource/buck-out/v2/gen/fbcode/14ceee714108d25d/pytorch/tritonbench/__run__/run#link-tree/__par__/meta_only/bootstrap.py", line 98, in run_as_main
    oss_run_as_main(
  File "/data/users/shawnzhong/fbsource/buck-out/v2/gen/fbcode/14ceee714108d25d/pytorch/tritonbench/__run__/run#link-tree/__par__/bootstrap.py", line 94, in run_as_main
    main()
  File "/data/users/shawnzhong/fbsource/buck-out/v2/gen/fbcode/14ceee714108d25d/pytorch/tritonbench/__run__/run#link-tree/pytorch/tritonbench/run.py", line 124, in run
    _run(args, extra_args)
  File "/data/users/shawnzhong/fbsource/buck-out/v2/gen/fbcode/14ceee714108d25d/pytorch/tritonbench/__run__/run#link-tree/pytorch/tritonbench/run.py", line 74, in _run
    opbench.plot()
  File "/data/users/shawnzhong/fbsource/buck-out/v2/gen/fbcode/14ceee714108d25d/pytorch/tritonbench/__run__/run#link-tree/tritonbench/operators/jagged_sum/operator.py", line 322, in plot
    os.mkdir(save_path)
FileNotFoundError: [Errno 2] No such file or directory: '/data/users/shawnzhong/fbsource/fbcode/pytorch/tritonbench/pytorch/tritonbench/tritonbench/operators/jagged_sum/jagged_sum_performance/jagged-sum-perf-var-sparsity-B-32-M-32-seqlen-1024'
```

One potential solution is to change `os.mkdir` to `os.makedirs`.

However, it turns out that the upstream already handles the creation of directires at https://github.com/triton-lang/triton/pull/2796.

Therefore, this diff removes the redundant `os.mkdir` to avoid the FileNotFoundError.

Reviewed By: xuzhao9

Differential Revision: D76829622

fbshipit-source-id: d222dd6b21fb6cfe0db41b2b21460da64dd253e8